### ISSUE TITLE
Add column filter to include adding unique ID

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/libhxl-python#199]
Based on the work mentioned here https://github.com/HXLStandard/libhxl-python/issues/197#issuecomment-438671669 it would be great to add a unique ID with an option to select which columns define uniqueness. Eg #date+week,#adm2,#indicator+category

**Comment by davidmegginson** [comment]
We can probably simplify this a bit, because the [Deduplicate rows filter](https://github.com/HXLStandard/hxl-proxy/wiki/Deduplicate-rows-filter) already lets you reduce the dataset to unique rows based a user-selected set of columns that define uniqueness. 

Or did you want the ability to add ideas to potentially-duplicate rows?

**Comment by davidmegginson** [comment]
@SimonbJohnson - with the new formula support from #202, would it make sense simply to add an md5() function that creates a hash of the specified values? e.g.

```md5(#org, #activity, #adm1)```
