### ISSUE TITLE
"is max" filter not working with numbers

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/libhxl-python#204]
This returns all weeks with a number and excludes blanks where I would expect just the largest number

https://proxy.hxlstandard.org/data/edit?filter01=select&select-query01-01=%23date%2Bweek+is+max&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ZCbB24L9wFrMfJYxokUMWKqTyQmi2LETxYMkmLGbtok%2Fedit%23gid%3D0

**Comment by davidmegginson** [comment]
This recipe is no longer crashing, so the second bug seems to be fixed now, but still need to figure out why its choosing multiple rows.

https://beta.proxy.hxlstandard.org/data/edit?filter01=merge&merge-url01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ZCbB24L9wFrMfJYxokUMWKqTyQmi2LETxYMkmLGbtok%2Fedit%23gid%3D0&merge-keys01=%23date&merge-tags01=%23date&filter02=select&select-query02-01=%23date%2Bweek+is+max&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vSrr9DRaC2fXzPdmOxLW-egSYtxmEp_RKoYGggt-zOKYXSx4RjPsM4EO19H7OJVX1esTtIoFvlKFWcn%2Fpub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv

**Comment by davidmegginson** [comment]
For the first issue, I think it's because @SimonbJohnson is using the #date hashtag, so libhxl is trying to normalise the numbers as dates before doing the comparison. When I change #date+week to #x_week, it works as expected:

https://beta.proxy.hxlstandard.org/data/edit?filter01=merge&merge-url01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ZCbB24L9wFrMfJYxokUMWKqTyQmi2LETxYMkmLGbtok%2Fedit%23gid%3D0&merge-keys01=%23date&merge-tags01=%23date&filter02=rename&rename-oldtag02=%23date%2Bweek&rename-newtag02=%23x_week&filter03=select&select-query03-01=%23x_week+is+max&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vSrr9DRaC2fXzPdmOxLW-egSYtxmEp_RKoYGggt-zOKYXSx4RjPsM4EO19H7OJVX1esTtIoFvlKFWcn%2Fpub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv

**Comment by davidmegginson** [comment]
When normalising dates, leave the original value unchanged when parsing fails. That yields the expected result in this case:

https://beta.proxy.hxlstandard.org/data/edit?filter01=merge&merge-url01=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2F1ZCbB24L9wFrMfJYxokUMWKqTyQmi2LETxYMkmLGbtok%2Fedit%23gid%3D0&merge-keys01=%23date&merge-tags01=%23date&filter02=select&select-query02-01=%23date%2Bweek+is+max&url=https%3A%2F%2Fdocs.google.com%2Fspreadsheets%2Fd%2Fe%2F2PACX-1vSrr9DRaC2fXzPdmOxLW-egSYtxmEp_RKoYGggt-zOKYXSx4RjPsM4EO19H7OJVX1esTtIoFvlKFWcn%2Fpub%3Fgid%3D0%26single%3Dtrue%26output%3Dcsv

**Comment by SimonbJohnson** [comment]
'Is Max' is doing a string comparison, so returning 9 rather than 23.  Is it then worth parsing date -> parse number and then fail condition?

**Comment by davidmegginson** [comment]
I will look into the number/date/etc handling -- thanks for the report.

**Comment by davidmegginson** [comment]
@SimonbJohnson - it's forcing a string comparison because the number appears under the #date hashtag, which means it will always be normalised (if possible) and then string-compared. I think we probably shouldn't have anything under #date that can't be normalised to an absolute date. Are these relative dates (e.g. week 1 of the crisis/project, week 2 of the crisis/project, etc)? If so, then HXL might need a new hashtag like #timeperiod or similar.

**Comment by SimonbJohnson** [comment]
Yes, these are epi weeks.  Roughly 1 to 52 throughout the year. We do have cases of #date+year which do sort in the right order due to the range.

**Comment by davidmegginson** [comment]
Hmm. We'd want to normalise them to ISO 2018W01, 2018W02, etc. It would be great if they started out that way, but I'll see what I can do with them. https://en.wikipedia.org/wiki/ISO_week_date

**Comment by davidmegginson** [comment]
Closing this issue, and opening #205 to deal specifically with week-number normalisation
