### ISSUE TITLE
Still failing on encoding error

### ISSUE THREAD

**Issue by davidmegginson** [HXLStandard/libhxl-python#271]
https://proxy.hxlstandard.org/data?dest=data_view&url=https%3A%2F%2Fdata.humdata.org%2Fdataset%2F51e35073-2d95-4e28-b53d-e34b37abb1b2%2Fresource%2Fff5f0c12-877e-43e6-afe8-b8b6cb8cbaf9%2Fdownload%2Fafghanistan-3w-operational-capacity-october-to-december-2020.csv

Error: 'utf-8' codec can't decode byte 0xa0 in position 7183: invalid start byte

**Comment by davidmegginson** [comment]
The exception is coming from the built-in csv module. The trick to avoid it is passing error="replace" to anything doing decoding, which will replace incorrectly-encoded characters with question marks.

**Comment by fititnt** [comment]
I'm getting this issue too on https://github.com/EticaAI/HXL-Data-Science-file-formats/issues/6, even after converting something outside libhxl-python to UTF8. But minutes ago I discovered that, without any changes, if is converted to UTF8 **with BOM**, it works.

```bash
fititnt@bravo:/workspace/git/EticaAI/HXL-Data-Science-file-formats$ hxlquickimport hxlquickimport_samples/MICRODADOS_ENEM_2019_head-n-1000_quick-utf8.csv
Traceback (most recent call last):
  File "/workspace/bin/hxlquickimport", line 406, in <module>
    hxlquickimport.execute(args)
  File "/workspace/bin/hxlquickimport", line 115, in execute
    with self.hxlhelper.make_source(args, stdin) as source:
  File "/workspace/bin/hxlquickimport", line 310, in make_source
    input = self.make_input(args, stdin)
  File "/workspace/bin/hxlquickimport", line 329, in make_input
    return hxl.io.make_input(
  File "/home/fititnt/.local/lib/python3.8/site-packages/hxl/io.py", line 440, in make_input
    return CSVInput(input, encoding=encoding)
  File "/home/fititnt/.local/lib/python3.8/site-packages/hxl/io.py", line 742, in __init__
    delimiter = CSVInput._detect_delimiter(input, encoding)
  File "/home/fititnt/.local/lib/python3.8/site-packages/hxl/io.py", line 765, in _detect_delimiter
    sample = input.peek(16384).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 4095: unexpected end of data
fititnt@bravo:/workspace/git/EticaAI/HXL-Data-Science-file-formats$ hxlquickimport hxlquickimport_samples/MICRODADOS_ENEM_2019_head-n-1000_quick-utf8-bom.csv | wc -l
1000
```

Also, I think I will wait for this merge to make new on importing. But something I will try to add to that tool is some way to allow user to specify the source encoding, since I'm not sure if this could be inferred from the libhxl-python alone.

---

Files just as reference. But maybe an updated version of this would become a new issue here on the HXLStandard/libhxl-python if a manage to be more specific.

[hxlquickimport-encoding-test-samples_v1.zip](https://github.com/HXLStandard/libhxl-python/files/5913125/hxlquickimport-encoding-test-samples_v1.zip)

**Comment by davidmegginson** [comment]
Thank you very much for the samples. They all pass now with recent commits to the dev branch. I did a diff on the output from the "quick" versions with and without the BOM after passing them through libhxl, and the only difference was the BOM itself (which gets passed through).  It's great to have the confirmation before we do our next release this week.
