### ISSUE TITLE
Fuzzy merging

### ISSUE THREAD

**Issue by SimonbJohnson** [HXLStandard/libhxl-python#50]
Allow joining on data sets uses a fuzzy match and a tolerance level

**Comment by davidmegginson** [comment]
This is an interesting challenge.  If it's not possible to use a hash, then the performance will drop from roughly O(n) to O(n²), which would be a very bad thing: in the region of a 100–1,000× performance penalty for a typical dataset.  We could try hashing on something like a SoundEx (there's probably a better choice that's not English-specific), but we still have the challenge of making sure that we have the _best_ match available: e.g. if both "bot" and "bat" are available, we want "bat" to match "bat", not the earlier "bot".

I'm going to leave this issue open for now and think about it a bit, but I suspect that a better solution might be to use hxlclean, hxlreplace, etc. to pre-normalise the shared keys the way you want.  That's what we did for the Guinea data.

**Comment by SimonbJohnson** [comment]
I think the fuzzy match would be used to generate the cleaning tables rather than doing it by hand, maybe a better name for this feature would be fuzzy clean to emphasise its use?  I believe the UN pcoder tool may do this and someone on my team has built themselves one.  I guess then it doesn't quite fit with the chained workflow, so not sure how well it fits in here.

**Comment by davidmegginson** [comment]
Fuzzy matching works well on a 1×1 iteractive basis — type in a name, the system looks for matches, then you pick one — but it can be trickier for large-scale batch processing, both because of the O(n²) performance, and because you can't get interactive user confirmation that you've made the right guess.

I'm going to retire this issue for now, but I think we should revisit it if/when we start building interactive tools for data encoding.
